package visaogrupo.com.br.modulo_visitacao.Views.Models.Class.Objetos

data class CarrinhoKit(    val lojaId: Int,
                           val clienteId: Int,
                           val kitCodigo: Int,
                           val operadorLogistigo: String,
                           val usuarioId: Int,
                           val uf: String,
                           val comissao: Double,
                           val comissaoPorcentagem: Double,
                           val marcasXComissoesId: Int,
                           val quantidade: Int,
                           val por: Double,
                           val valorDe: Double,
                           val grupoCodigo: Int,
                           val desconto: Double,
                           val codListaPrecoSync: Int,
                           var valortotal:Double,
                           val nomeKit:String,
                           val nomeLoja:String,
                           val razaoSolcial:String,
                           val cnpj:String,
                           val data:String,
                           val valorMinimoLoja:Double,
                           val FormaPagamentoExclusiva:Int,
                           val QtdMinima_Operador:Int,
                           val QtdMaxima_Operador:Int,
                           val  RegraPrazo:Int,
                           val  LojaTipo:Int,
                           val porecentagem:Double,
                           var listProdutoKit: MutableList<KitProtudos>? = null,
                           var numerPedido:Int
                  )
