package visaogrupo.com.br.modulo_visitacao.Views.Models.Class.Objetos

data class Lojas(
    val loja_id: Int,
    val nome: String,
    val MinimoUnidades: Int,
    val MinimoValor: Double,
    val LojaTipo: Int,
    val tipo: String,
    val LogoHome: String ?,
    val Distribuidora: Int,
    val Loja_Desconto: String,
    val DescontoMaximo: Double,
    val Tipo_Imposto_ID: Int,
    val Tipo_Imposto: Int,
    val Libera_Fidelidade: String,
    val Qtd_ProdutosLoja: Int,
    val Loja_Tablet: String,
    val Venda_Tipo_id: Int,
    val Data_Inicio: String,
    val Data_Fim: String ?,
    val Portal_Tablet: Int,
    val Qtd_Minima_Operador: Int,
    val Qtd_Maxima_Operador: Int,
    val Loja_Online: String,
    val Minimo_Aprovacao: Double,
    val Valida_Estoque: String,
    val Loja_Preco: String,
    val Exibe_Estoque: Int,
    val ANR :Int,
    val RegraPrazoMedio :Int,
    val Base64:String
)