package visaogrupo.com.br.modulo_visitacao.Views.Models.Class.Objetos

data class PedidoFinalizado(
        val pedidoID: Long,
        val lojaId: Int,
        val clienteId: Int,
        val operadorLogistico: String,
        val usuarioId: Int,
        val uf: String,
        val comissao: Double?,
        val comissaoPorcentagem: Double?,
        val marcasXComissoesId: Int?,
        val produtoCodigo: Int?,
        val barra: String?,
        val quantidade: Int?,
        val pf: Double,
        val valor: Double,
        val valorOriginal: Double,
        val grupoCodigo: Int?,
        val desconto: Double,
        val descontoOriginal: Double,
        val st: Double?,
        val formalizacao: String?,
        val codListaPrecoSync: Int?,
        val valorTotal: Double?,
        val nome: String?,
        val apontadorCodigo: String?,
        val nomeLoja: String?,
        val razaoSocial: String?,
        val cnpj: String?,
        val dataPedido: String?,
        val valorMinimoLoja: Double?,
        val base64: String?,
        val caixaPadrao: Int?,
        val pmc: Double?,
        val qtdMinimaOperador: Int?,
        val qtdMaximaOperador: Int?,
        val anr: Boolean?,
        val pedidoEnviado: Boolean?,
        val formaDePagamento: String?,
        val numeroPedido: String?,
        val operadoresPedidos: String?,
        val formaPagamentoExclusiva: Int?,
        val chave:String?,
        val justificativaANR:String,
        val TipoLoja:Int,
        val RegraPrazo:Int,
        val quantidadeMaximaOpl:Int,
        val kitCodigo:Int,
        val de:Double,
        val por:Double,
        val nomekit:String,
        val kit:Int
):java.io.Serializable

